# Generated by Django 6.1.1 on 2026-09-26 09:26

from django.db import migrations


def admin_create(apps,schema_editor):
    User= apps.get_model('users', 'User')
    if not User.objects.filter(username="admin").exists():
        User.objects.create(
            username="admin",email="admin@admin.admin",
            password="adminpassword123",role="admin",
            approved=True,first_name="Admin",last_name="Admin",
            taxNumber="000000000",postcode=00000
            )

class Migration(migrations.Migration):

    dependencies = [
        ('users',"0002_user_latitude_user_longitude",),
    ]

    operations = [
        migrations.RunPython(admin_create)
        ]
