# Generated by Django 6.1 on 2026-08-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_latitude_user_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='requested_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('guest', 'Guest'), ('organizer', 'Organizer'), ('participant', 'Participant')], default='guest', max_length=20, null=True),
        ),
    ]
