import { User } from "@/types/user";

export const mockUsers: User[] = [
  {
    userid: 1,
    username: "jdoe",
    password: "••••••••",
    role: "adimn",
    approved: true,
    name: "John",
    surename: "Doe",
    email: "john.doe@example.com",
    telephone: 6912345678,
    address: "12 Syntagma Sq, Athens",
    taxNumber: "123456789",
  },
  {
    userid: 2,
    username: "mpapadopoulou",
    password: "••••••••",
    role: "orginiser",
    approved: true,
    name: "Maria",
    surename: "Papadopoulou",
    email: "maria.papadopoulou@example.com",
    telephone: 6923456789,
    address: "45 Egnatia St, Thessaloniki",
    taxNumber: "234567891",
  },
  {
    userid: 3,
    username: "gnikolaou",
    password: "••••••••",
    role: "orginiser",
    approved: false,
    name: "George",
    surename: "Nikolaou",
    email: "george.nikolaou@example.com",
    telephone: 6934567890,
    address: "8 Ermou St, Patras",
    taxNumber: "345678912",
  },
  {
    userid: 4,
    username: "ekonstantinou",
    password: "••••••••",
    role: "participant",
    approved: true,
    name: "Eleni",
    surename: "Konstantinou",
    email: "eleni.konstantinou@example.com",
    telephone: 6945678901,
    address: "3 Akadimias St, Athens",
    taxNumber: "456789123",
  },
  {
    userid: 5,
    username: "dvasiliou",
    password: "••••••••",
    role: "participant",
    approved: false,
    name: "Dimitris",
    surename: "Vasiliou",
    email: "dimitris.vasiliou@example.com",
    telephone: 6956789012,
    address: "19 Tsimiski St, Thessaloniki",
    taxNumber: "567891234",
  },
  {
    userid: 6,
    username: "avlachou",
    password: "••••••••",
    role: "guest",
    approved: true,
    name: "Anna",
    surename: "Vlachou",
    email: "anna.vlachou@example.com",
    telephone: 6967890123,
    address: "27 Panepistimiou St, Athens",
    taxNumber: "678912345",
  },
  {
    userid: 7,
    username: "spapas",
    password: "••••••••",
    role: "guest",
    approved: false,
    name: "Stavros",
    surename: "Papas",
    email: "stavros.papas@example.com",
    telephone: 6978901234,
    address: "5 Korai St, Larissa",
    taxNumber: "789123456",
  },
];
